apiVersion: v1
kind: Pod
metadata:
  name: rating-producer
  labels:
    app: web
spec:
  containers:
    - name: test-end
      image: f2js/rating-producer
      ports:
        - containerPort: 9000
      env:
        - name: CLUSTER_IP
          value: ${CLUSTER_IP}
      hostAliases:
        - ip: ${CLUSTER_IP}
          hostnames:
            - "kafka-broker"
